# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumb:
            quality: 75
            filters:
                fixed:
                    width: 360
                    height: 230
        medium:
            quality: 75
            filters:
                fixed:
                    width: 800
                    height: 530